name = "steaminviter"
main = "src/index.ts"
compatibility_date = "2024-09-19"

[assets]
directory = "out"
binding = "ASSETS"

[observability.logs]
enabled = true

[env.production]
name = "steaminviter"
route = "steaminviter.app/*"

[env.preview]
name = "steaminviter-preview"
